/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabi Curiel
 */
public class ViewCyD extends javax.swing.JFrame {

    /**
     * Creates new form ViewCyD
     */
    public ViewCyD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta_txt = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_abrir = new javax.swing.JMenuItem();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cifrar = new javax.swing.JMenuItem();
        jmi_decifrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jta_txt.setColumns(20);
        jta_txt.setRows(5);
        jScrollPane1.setViewportView(jta_txt);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));

        jm_archivo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, null));
        jm_archivo.setText("Archivo");
        jm_archivo.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N

        jmi_abrir.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jmi_abrir.setText("Abrir");
        jm_archivo.add(jmi_abrir);

        jmi_guardar.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jmi_guardar.setText("Guardar");
        jm_archivo.add(jmi_guardar);

        jmi_cifrar.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jmi_cifrar.setText("Cifrar");
        jmi_cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cifrarActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_cifrar);

        jmi_decifrar.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jmi_decifrar.setText("Decifrar");
        jm_archivo.add(jmi_decifrar);

        jMenuBar1.add(jm_archivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cifrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_cifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCyD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCyD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCyD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCyD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCyD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JMenu jm_archivo;
    public javax.swing.JMenuItem jmi_abrir;
    public javax.swing.JMenuItem jmi_cifrar;
    public javax.swing.JMenuItem jmi_decifrar;
    public javax.swing.JMenuItem jmi_guardar;
    public javax.swing.JTextArea jta_txt;
    // End of variables declaration//GEN-END:variables
}
